### ISSUE TITLE
Task "gulp serve" throws an error on Windows "google chrome not foun

### ISSUE THREAD

**Issue by Bruce17** [doroppu/yoso-gulp#20]
Using `gulp serve` on Win10 throws an error message:

![image](https://cloud.githubusercontent.com/assets/5036995/10304405/34517588-6c1a-11e5-8673-66ec34fff38d.png)

**Comment by nahody** [comment]
Just change the settings inside your gulpfile.js on project root. 

'google-chrome' // Linux 
'chrome' // Windows 
'google chrome' or 'Google Chrome' // OSX

**Comment by Bruce17** [comment]
Please add this information to the readme file
Am 23.10.2015 12:19 schrieb "nahody" <notifications@github.com>:

**Comment by nahody** [comment]
Is done. Please close.
